# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://168.138.40.98:3306/cpingblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: admin
    password: Pz+20180101
shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379


